import esbuild from "esbuild";
import process from "node:process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const buildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ['main.ts', 'styles/styles.css'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        'tslib',
        ...builtins],
    format: 'cjs',
    target: 'es2018',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outdir: '.',
    entryNames: '[name]',
};

if (!prod) {
    // For development, set up watch mode
    const context = await esbuild.context(buildOptions);
    await context.watch();
    console.log('⚡ esbuild is running in watch mode ⚡');
} else {
    // For production, just build once
    await esbuild.build(buildOptions);
    console.log('⚡ esbuild build complete ⚡');
}
